services:
  neo4j:
    image: neo4j:5.24-community
    container_name: telco_kg_neo4j
    ports:
      - "7474:7474" # HTTP browser UI
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/telco12345
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
