"""Real fault-diagnosis data from NetManAIOps/DejaVu (ESEC/FSE'22, Li et al.,
Tsinghua) -- used as a real-data, cross-domain check for the KG + rule engine
+ GraphRAG pipeline built for the (synthetic) telecom scenarios.

Source: https://zenodo.org/records/6955909 (DOI 10.5281/zenodo.6955909),
license CC-BY 4.0 -- redistribution of this derived subset is permitted with
attribution, unlike the other real datasets considered (see README.md for
the full data-sourcing story: NetRCA's challenge infra was dead, TeleLogs is
gated + explicitly non-redistributable).

IMPORTANT CAVEAT: this is real microservice/infrastructure fault data
(Docker containers, DB instances, OS hosts calling each other), NOT telecom
network data. It is used here because its structure -- a real dependency
DAG with real fault injection and real ground-truth root-cause labels -- is
the same graph-theoretic shape (dependency graph + fault propagation + root
cause localization) as the telecom cascade problem this project targets, so
it is a legitimate generalization check, not a telecom dataset.

All incidents in this dataset are single-device, non-cascading faults
(root cause is always the same device that shows the fault) -- i.e. they
exercise the "isolated device fault" rule / structural-diagnosis path on a
messy real multi-parent DAG (unlike the synthetic telecom scenarios, which
specifically also test cascading multi-device attribution).

Regenerate with: python scripts/fetch_dejavu.py -- do not hand-edit.
"""

DEVICES = [
    {"id": 'db_003', "type": 'db', "name": 'db_003', "depends_on": []},
    {"id": 'db_007', "type": 'db', "name": 'db_007', "depends_on": []},
    {"id": 'db_009', "type": 'db', "name": 'db_009', "depends_on": []},
    {"id": 'docker_001', "type": 'docker', "name": 'docker_001', "depends_on": ['db_007', 'db_009', 'docker_007', 'docker_008', 'os_017']},
    {"id": 'docker_002', "type": 'docker', "name": 'docker_002', "depends_on": ['db_007', 'db_009', 'docker_007', 'docker_008', 'os_018']},
    {"id": 'docker_003', "type": 'docker', "name": 'docker_003', "depends_on": ['db_007', 'db_009', 'docker_005', 'docker_006', 'os_019']},
    {"id": 'docker_004', "type": 'docker', "name": 'docker_004', "depends_on": ['db_007', 'db_009', 'docker_005', 'docker_006', 'os_020']},
    {"id": 'docker_005', "type": 'docker', "name": 'docker_005', "depends_on": ['db_003', 'os_017']},
    {"id": 'docker_006', "type": 'docker', "name": 'docker_006', "depends_on": ['db_003', 'os_018']},
    {"id": 'docker_007', "type": 'docker', "name": 'docker_007', "depends_on": ['db_003', 'os_019']},
    {"id": 'docker_008', "type": 'docker', "name": 'docker_008', "depends_on": ['db_003', 'os_020']},
    {"id": 'os_017', "type": 'os', "name": 'os_017', "depends_on": []},
    {"id": 'os_018', "type": 'os', "name": 'os_018', "depends_on": []},
    {"id": 'os_019', "type": 'os', "name": 'os_019', "depends_on": []},
    {"id": 'os_020', "type": 'os', "name": 'os_020', "depends_on": []},
    {"id": 'os_021', "type": 'osb', "name": 'os_021', "depends_on": ['docker_003', 'docker_004']},
    {"id": 'os_022', "type": 'osb', "name": 'os_022', "depends_on": ['docker_001', 'docker_002']},
]

INCIDENTS = [
    {
        "id": 'DEJAVU-001',
        "name": 'Sự cố #1: quá tải CPU tại docker_003 (container)',
        "description": 'Sự cố thật #1 (dataset DejaVu): thiết bị docker_003 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 10/04/2020 16:05 UTC. Nguyên nhân gốc rễ (ground truth): docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-002',
        "name": 'Sự cố #2: độ trễ mạng cao bất thường tại docker_002 (container)',
        "description": 'Sự cố thật #2 (dataset DejaVu): thiết bị docker_002 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 10/04/2020 16:35 UTC. Nguyên nhân gốc rễ (ground truth): docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-003',
        "name": 'Sự cố #3: độ trễ mạng cao bất thường tại docker_001 (container)',
        "description": 'Sự cố thật #3 (dataset DejaVu): thiết bị docker_001 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 10/04/2020 17:10 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-004',
        "name": 'Sự cố #4: quá tải CPU tại docker_004 (container)',
        "description": 'Sự cố thật #4 (dataset DejaVu): thiết bị docker_004 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 10/04/2020 17:40 UTC. Nguyên nhân gốc rễ (ground truth): docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-005',
        "name": 'Sự cố #5: vượt giới hạn số kết nối database tại db_007 (database)',
        "description": 'Sự cố thật #5 (dataset DejaVu): thiết bị db_007 (database) gặp \'vượt giới hạn số kết nối database\' (mã gốc trong dữ liệu: "db connection limit"). Ghi nhận lúc 10/04/2020 18:15 UTC. Nguyên nhân gốc rễ (ground truth): db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-006',
        "name": 'Sự cố #6: quá tải CPU tại docker_002 (container)',
        "description": 'Sự cố thật #6 (dataset DejaVu): thiết bị docker_002 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 10/04/2020 18:50 UTC. Nguyên nhân gốc rễ (ground truth): docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-007',
        "name": 'Sự cố #7: độ trễ mạng cao bất thường tại docker_003 (container)',
        "description": 'Sự cố thật #7 (dataset DejaVu): thiết bị docker_003 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 10/04/2020 19:20 UTC. Nguyên nhân gốc rễ (ground truth): docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-008',
        "name": 'Sự cố #8: mất gói tin trên mạng tại docker_003 (container)',
        "description": 'Sự cố thật #8 (dataset DejaVu): thiết bị docker_003 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 10/04/2020 19:55 UTC. Nguyên nhân gốc rễ (ground truth): docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-009',
        "name": 'Sự cố #9: quá tải CPU tại docker_008 (container)',
        "description": 'Sự cố thật #9 (dataset DejaVu): thiết bị docker_008 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 10/04/2020 20:40 UTC. Nguyên nhân gốc rễ (ground truth): docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-010',
        "name": 'Sự cố #10: mất gói tin trên mạng tại docker_007 (container)',
        "description": 'Sự cố thật #10 (dataset DejaVu): thiết bị docker_007 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 10/04/2020 21:05 UTC. Nguyên nhân gốc rễ (ground truth): docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-011',
        "name": 'Sự cố #11: mất kết nối / đóng phiên database tại db_003 (database)',
        "description": 'Sự cố thật #11 (dataset DejaVu): thiết bị db_003 (database) gặp \'mất kết nối / đóng phiên database\' (mã gốc trong dữ liệu: "db  close"). Ghi nhận lúc 10/04/2020 21:45 UTC. Nguyên nhân gốc rễ (ground truth): db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-012',
        "name": 'Sự cố #12: mất kết nối / đóng phiên database tại db_003 (database)',
        "description": 'Sự cố thật #12 (dataset DejaVu): thiết bị db_003 (database) gặp \'mất kết nối / đóng phiên database\' (mã gốc trong dữ liệu: "db  close"). Ghi nhận lúc 21/05/2020 16:07 UTC. Nguyên nhân gốc rễ (ground truth): db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-013',
        "name": 'Sự cố #13: quá tải CPU tại docker_001 (container)',
        "description": 'Sự cố thật #13 (dataset DejaVu): thiết bị docker_001 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 21/05/2020 16:48 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-014',
        "name": 'Sự cố #14: độ trễ mạng cao bất thường tại docker_005 (container)',
        "description": 'Sự cố thật #14 (dataset DejaVu): thiết bị docker_005 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 21/05/2020 17:18 UTC. Nguyên nhân gốc rễ (ground truth): docker_005.',
        "alarms": [{'device': 'docker_005', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-015',
        "name": 'Sự cố #15: độ trễ mạng cao bất thường tại os_018 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #15 (dataset DejaVu): thiết bị os_018 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 21/05/2020 17:48 UTC. Nguyên nhân gốc rễ (ground truth): os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-016',
        "name": 'Sự cố #16: quá tải CPU tại docker_005 (container)',
        "description": 'Sự cố thật #16 (dataset DejaVu): thiết bị docker_005 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 21/05/2020 18:18 UTC. Nguyên nhân gốc rễ (ground truth): docker_005.',
        "alarms": [{'device': 'docker_005', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-017',
        "name": 'Sự cố #17: độ trễ mạng cao bất thường tại docker_007 (container)',
        "description": 'Sự cố thật #17 (dataset DejaVu): thiết bị docker_007 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 21/05/2020 21:18 UTC. Nguyên nhân gốc rễ (ground truth): docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-018',
        "name": 'Sự cố #18: độ trễ mạng cao bất thường tại docker_006 (container)',
        "description": 'Sự cố thật #18 (dataset DejaVu): thiết bị docker_006 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 21/05/2020 21:48 UTC. Nguyên nhân gốc rễ (ground truth): docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-019',
        "name": 'Sự cố #19: quá tải CPU tại docker_004 (container)',
        "description": 'Sự cố thật #19 (dataset DejaVu): thiết bị docker_004 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 22/05/2020 16:05 UTC. Nguyên nhân gốc rễ (ground truth): docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-020',
        "name": 'Sự cố #20: vượt giới hạn số kết nối database tại db_003 (database)',
        "description": 'Sự cố thật #20 (dataset DejaVu): thiết bị db_003 (database) gặp \'vượt giới hạn số kết nối database\' (mã gốc trong dữ liệu: "db connection limit"). Ghi nhận lúc 22/05/2020 16:40 UTC. Nguyên nhân gốc rễ (ground truth): db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-021',
        "name": 'Sự cố #21: mất gói tin trên mạng tại os_021 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #21 (dataset DejaVu): thiết bị os_021 (máy chủ vật lý (host)) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 22/05/2020 17:16 UTC. Nguyên nhân gốc rễ (ground truth): os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-022',
        "name": 'Sự cố #22: độ trễ mạng cao bất thường tại docker_006 (container)',
        "description": 'Sự cố thật #22 (dataset DejaVu): thiết bị docker_006 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 22/05/2020 19:00 UTC. Nguyên nhân gốc rễ (ground truth): docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-023',
        "name": 'Sự cố #23: độ trễ mạng cao bất thường tại os_021 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #23 (dataset DejaVu): thiết bị os_021 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 22/05/2020 19:36 UTC. Nguyên nhân gốc rễ (ground truth): os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-024',
        "name": 'Sự cố #24: quá tải CPU tại docker_006 (container)',
        "description": 'Sự cố thật #24 (dataset DejaVu): thiết bị docker_006 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 22/05/2020 20:47 UTC. Nguyên nhân gốc rễ (ground truth): docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-025',
        "name": 'Sự cố #25: độ trễ mạng cao bất thường tại docker_005 (container)',
        "description": 'Sự cố thật #25 (dataset DejaVu): thiết bị docker_005 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 22/05/2020 21:20 UTC. Nguyên nhân gốc rễ (ground truth): docker_005.',
        "alarms": [{'device': 'docker_005', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-026',
        "name": 'Sự cố #26: mất gói tin trên mạng tại docker_007 (container)',
        "description": 'Sự cố thật #26 (dataset DejaVu): thiết bị docker_007 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 22/05/2020 21:55 UTC. Nguyên nhân gốc rễ (ground truth): docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-027',
        "name": 'Sự cố #27: mất gói tin trên mạng tại docker_004 (container)',
        "description": 'Sự cố thật #27 (dataset DejaVu): thiết bị docker_004 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 23/05/2020 16:17 UTC. Nguyên nhân gốc rễ (ground truth): docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-028',
        "name": 'Sự cố #28: mất kết nối / đóng phiên database tại db_007 (database)',
        "description": 'Sự cố thật #28 (dataset DejaVu): thiết bị db_007 (database) gặp \'mất kết nối / đóng phiên database\' (mã gốc trong dữ liệu: "db  close"). Ghi nhận lúc 23/05/2020 17:47 UTC. Nguyên nhân gốc rễ (ground truth): db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-029',
        "name": 'Sự cố #29: mất gói tin trên mạng tại docker_002 (container)',
        "description": 'Sự cố thật #29 (dataset DejaVu): thiết bị docker_002 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 23/05/2020 18:47 UTC. Nguyên nhân gốc rễ (ground truth): docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-030',
        "name": 'Sự cố #30: quá tải CPU tại docker_003 (container)',
        "description": 'Sự cố thật #30 (dataset DejaVu): thiết bị docker_003 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 23/05/2020 19:17 UTC. Nguyên nhân gốc rễ (ground truth): docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-031',
        "name": 'Sự cố #31: quá tải CPU tại docker_006 (container)',
        "description": 'Sự cố thật #31 (dataset DejaVu): thiết bị docker_006 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 23/05/2020 20:17 UTC. Nguyên nhân gốc rễ (ground truth): docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-032',
        "name": 'Sự cố #32: độ trễ mạng cao bất thường tại docker_004 (container)',
        "description": 'Sự cố thật #32 (dataset DejaVu): thiết bị docker_004 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 23/05/2020 20:47 UTC. Nguyên nhân gốc rễ (ground truth): docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-033',
        "name": 'Sự cố #33: độ trễ mạng cao bất thường tại os_020 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #33 (dataset DejaVu): thiết bị os_020 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 24/05/2020 17:47 UTC. Nguyên nhân gốc rễ (ground truth): os_020.',
        "alarms": [{'device': 'os_020', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_020',
    },
    {
        "id": 'DEJAVU-034',
        "name": 'Sự cố #34: mất gói tin trên mạng tại os_017 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #34 (dataset DejaVu): thiết bị os_017 (máy chủ vật lý (host)) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 24/05/2020 19:47 UTC. Nguyên nhân gốc rễ (ground truth): os_017.',
        "alarms": [{'device': 'os_017', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_017',
    },
    {
        "id": 'DEJAVU-035',
        "name": 'Sự cố #35: mất kết nối / đóng phiên database tại db_003 (database)',
        "description": 'Sự cố thật #35 (dataset DejaVu): thiết bị db_003 (database) gặp \'mất kết nối / đóng phiên database\' (mã gốc trong dữ liệu: "db  close"). Ghi nhận lúc 24/05/2020 20:47 UTC. Nguyên nhân gốc rễ (ground truth): db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-036',
        "name": 'Sự cố #36: mất gói tin trên mạng tại docker_003 (container)',
        "description": 'Sự cố thật #36 (dataset DejaVu): thiết bị docker_003 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 25/05/2020 16:32 UTC. Nguyên nhân gốc rễ (ground truth): docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-037',
        "name": 'Sự cố #37: vượt giới hạn số kết nối database tại db_007 (database)',
        "description": 'Sự cố thật #37 (dataset DejaVu): thiết bị db_007 (database) gặp \'vượt giới hạn số kết nối database\' (mã gốc trong dữ liệu: "db connection limit"). Ghi nhận lúc 25/05/2020 18:09 UTC. Nguyên nhân gốc rễ (ground truth): db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-038',
        "name": 'Sự cố #38: quá tải CPU tại docker_008 (container)',
        "description": 'Sự cố thật #38 (dataset DejaVu): thiết bị docker_008 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 25/05/2020 18:39 UTC. Nguyên nhân gốc rễ (ground truth): docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-039',
        "name": 'Sự cố #39: độ trễ mạng cao bất thường tại os_021 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #39 (dataset DejaVu): thiết bị os_021 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 25/05/2020 19:09 UTC. Nguyên nhân gốc rễ (ground truth): os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-040',
        "name": 'Sự cố #40: mất gói tin trên mạng tại os_018 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #40 (dataset DejaVu): thiết bị os_018 (máy chủ vật lý (host)) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 25/05/2020 19:39 UTC. Nguyên nhân gốc rễ (ground truth): os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-041',
        "name": 'Sự cố #41: độ trễ mạng cao bất thường tại os_020 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #41 (dataset DejaVu): thiết bị os_020 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 25/05/2020 20:15 UTC. Nguyên nhân gốc rễ (ground truth): os_020.',
        "alarms": [{'device': 'os_020', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_020',
    },
    {
        "id": 'DEJAVU-042',
        "name": 'Sự cố #42: quá tải CPU tại docker_002 (container)',
        "description": 'Sự cố thật #42 (dataset DejaVu): thiết bị docker_002 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 25/05/2020 21:15 UTC. Nguyên nhân gốc rễ (ground truth): docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-043',
        "name": 'Sự cố #43: độ trễ mạng cao bất thường tại os_018 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #43 (dataset DejaVu): thiết bị os_018 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 26/05/2020 16:23 UTC. Nguyên nhân gốc rễ (ground truth): os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-044',
        "name": 'Sự cố #44: độ trễ mạng cao bất thường tại os_017 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #44 (dataset DejaVu): thiết bị os_017 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 26/05/2020 16:53 UTC. Nguyên nhân gốc rễ (ground truth): os_017.',
        "alarms": [{'device': 'os_017', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_017',
    },
    {
        "id": 'DEJAVU-045',
        "name": 'Sự cố #45: quá tải CPU tại docker_006 (container)',
        "description": 'Sự cố thật #45 (dataset DejaVu): thiết bị docker_006 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 26/05/2020 17:23 UTC. Nguyên nhân gốc rễ (ground truth): docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-046',
        "name": 'Sự cố #46: vượt giới hạn số kết nối database tại db_003 (database)',
        "description": 'Sự cố thật #46 (dataset DejaVu): thiết bị db_003 (database) gặp \'vượt giới hạn số kết nối database\' (mã gốc trong dữ liệu: "db connection limit"). Ghi nhận lúc 26/05/2020 17:53 UTC. Nguyên nhân gốc rễ (ground truth): db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-047',
        "name": 'Sự cố #47: mất kết nối / đóng phiên database tại db_007 (database)',
        "description": 'Sự cố thật #47 (dataset DejaVu): thiết bị db_007 (database) gặp \'mất kết nối / đóng phiên database\' (mã gốc trong dữ liệu: "db  close"). Ghi nhận lúc 26/05/2020 18:23 UTC. Nguyên nhân gốc rễ (ground truth): db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-048',
        "name": 'Sự cố #48: vượt giới hạn số kết nối database tại db_007 (database)',
        "description": 'Sự cố thật #48 (dataset DejaVu): thiết bị db_007 (database) gặp \'vượt giới hạn số kết nối database\' (mã gốc trong dữ liệu: "db connection limit"). Ghi nhận lúc 26/05/2020 18:53 UTC. Nguyên nhân gốc rễ (ground truth): db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-049',
        "name": 'Sự cố #49: độ trễ mạng cao bất thường tại docker_001 (container)',
        "description": 'Sự cố thật #49 (dataset DejaVu): thiết bị docker_001 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 26/05/2020 19:23 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-050',
        "name": 'Sự cố #50: mất gói tin trên mạng tại docker_007 (container)',
        "description": 'Sự cố thật #50 (dataset DejaVu): thiết bị docker_007 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 26/05/2020 20:39 UTC. Nguyên nhân gốc rễ (ground truth): docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-051',
        "name": 'Sự cố #51: quá tải CPU tại docker_001 (container)',
        "description": 'Sự cố thật #51 (dataset DejaVu): thiết bị docker_001 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 26/05/2020 21:09 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-052',
        "name": 'Sự cố #52: độ trễ mạng cao bất thường tại os_021 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #52 (dataset DejaVu): thiết bị os_021 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 26/05/2020 21:39 UTC. Nguyên nhân gốc rễ (ground truth): os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-053',
        "name": 'Sự cố #53: quá tải CPU tại docker_001 (container)',
        "description": 'Sự cố thật #53 (dataset DejaVu): thiết bị docker_001 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 27/05/2020 16:47 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-054',
        "name": 'Sự cố #54: độ trễ mạng cao bất thường tại docker_001 (container)',
        "description": 'Sự cố thật #54 (dataset DejaVu): thiết bị docker_001 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 27/05/2020 17:17 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-055',
        "name": 'Sự cố #55: độ trễ mạng cao bất thường tại docker_001 (container)',
        "description": 'Sự cố thật #55 (dataset DejaVu): thiết bị docker_001 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 27/05/2020 19:17 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-056',
        "name": 'Sự cố #56: mất gói tin trên mạng tại os_018 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #56 (dataset DejaVu): thiết bị os_018 (máy chủ vật lý (host)) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 27/05/2020 19:47 UTC. Nguyên nhân gốc rễ (ground truth): os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-057',
        "name": 'Sự cố #57: mất gói tin trên mạng tại docker_008 (container)',
        "description": 'Sự cố thật #57 (dataset DejaVu): thiết bị docker_008 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 27/05/2020 21:17 UTC. Nguyên nhân gốc rễ (ground truth): docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-058',
        "name": 'Sự cố #58: vượt giới hạn số kết nối database tại db_003 (database)',
        "description": 'Sự cố thật #58 (dataset DejaVu): thiết bị db_003 (database) gặp \'vượt giới hạn số kết nối database\' (mã gốc trong dữ liệu: "db connection limit"). Ghi nhận lúc 28/05/2020 18:11 UTC. Nguyên nhân gốc rễ (ground truth): db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-059',
        "name": 'Sự cố #59: quá tải CPU tại docker_008 (container)',
        "description": 'Sự cố thật #59 (dataset DejaVu): thiết bị docker_008 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 28/05/2020 18:41 UTC. Nguyên nhân gốc rễ (ground truth): docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-060',
        "name": 'Sự cố #60: quá tải CPU tại docker_001 (container)',
        "description": 'Sự cố thật #60 (dataset DejaVu): thiết bị docker_001 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 28/05/2020 19:41 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-061',
        "name": 'Sự cố #61: độ trễ mạng cao bất thường tại docker_006 (container)',
        "description": 'Sự cố thật #61 (dataset DejaVu): thiết bị docker_006 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 28/05/2020 21:11 UTC. Nguyên nhân gốc rễ (ground truth): docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-062',
        "name": 'Sự cố #62: mất gói tin trên mạng tại os_021 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #62 (dataset DejaVu): thiết bị os_021 (máy chủ vật lý (host)) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 29/05/2020 16:13 UTC. Nguyên nhân gốc rễ (ground truth): os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-063',
        "name": 'Sự cố #63: mất gói tin trên mạng tại docker_005 (container)',
        "description": 'Sự cố thật #63 (dataset DejaVu): thiết bị docker_005 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 29/05/2020 16:43 UTC. Nguyên nhân gốc rễ (ground truth): docker_005.',
        "alarms": [{'device': 'docker_005', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-064',
        "name": 'Sự cố #64: mất gói tin trên mạng tại docker_001 (container)',
        "description": 'Sự cố thật #64 (dataset DejaVu): thiết bị docker_001 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 29/05/2020 18:13 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-065',
        "name": 'Sự cố #65: độ trễ mạng cao bất thường tại os_020 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #65 (dataset DejaVu): thiết bị os_020 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 29/05/2020 19:43 UTC. Nguyên nhân gốc rễ (ground truth): os_020.',
        "alarms": [{'device': 'os_020', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_020',
    },
    {
        "id": 'DEJAVU-066',
        "name": 'Sự cố #66: quá tải CPU tại docker_002 (container)',
        "description": 'Sự cố thật #66 (dataset DejaVu): thiết bị docker_002 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 29/05/2020 20:13 UTC. Nguyên nhân gốc rễ (ground truth): docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-067',
        "name": 'Sự cố #67: mất gói tin trên mạng tại os_018 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #67 (dataset DejaVu): thiết bị os_018 (máy chủ vật lý (host)) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 29/05/2020 21:13 UTC. Nguyên nhân gốc rễ (ground truth): os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-068',
        "name": 'Sự cố #68: độ trễ mạng cao bất thường tại docker_002 (container)',
        "description": 'Sự cố thật #68 (dataset DejaVu): thiết bị docker_002 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 29/05/2020 21:43 UTC. Nguyên nhân gốc rễ (ground truth): docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-069',
        "name": 'Sự cố #69: độ trễ mạng cao bất thường tại docker_007 (container)',
        "description": 'Sự cố thật #69 (dataset DejaVu): thiết bị docker_007 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 30/05/2020 16:17 UTC. Nguyên nhân gốc rễ (ground truth): docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-070',
        "name": 'Sự cố #70: độ trễ mạng cao bất thường tại docker_001 (container)',
        "description": 'Sự cố thật #70 (dataset DejaVu): thiết bị docker_001 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 30/05/2020 16:47 UTC. Nguyên nhân gốc rễ (ground truth): docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-071',
        "name": 'Sự cố #71: mất gói tin trên mạng tại docker_008 (container)',
        "description": 'Sự cố thật #71 (dataset DejaVu): thiết bị docker_008 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 30/05/2020 17:47 UTC. Nguyên nhân gốc rễ (ground truth): docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-072',
        "name": 'Sự cố #72: độ trễ mạng cao bất thường tại docker_008 (container)',
        "description": 'Sự cố thật #72 (dataset DejaVu): thiết bị docker_008 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 30/05/2020 18:17 UTC. Nguyên nhân gốc rễ (ground truth): docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-073',
        "name": 'Sự cố #73: độ trễ mạng cao bất thường tại os_021 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #73 (dataset DejaVu): thiết bị os_021 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 30/05/2020 18:47 UTC. Nguyên nhân gốc rễ (ground truth): os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-074',
        "name": 'Sự cố #74: độ trễ mạng cao bất thường tại os_017 (máy chủ vật lý (host))',
        "description": 'Sự cố thật #74 (dataset DejaVu): thiết bị os_017 (máy chủ vật lý (host)) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 30/05/2020 19:17 UTC. Nguyên nhân gốc rễ (ground truth): os_017.',
        "alarms": [{'device': 'os_017', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_017',
    },
    {
        "id": 'DEJAVU-075',
        "name": 'Sự cố #75: vượt giới hạn số kết nối database tại db_003 (database)',
        "description": 'Sự cố thật #75 (dataset DejaVu): thiết bị db_003 (database) gặp \'vượt giới hạn số kết nối database\' (mã gốc trong dữ liệu: "db connection limit"). Ghi nhận lúc 30/05/2020 19:47 UTC. Nguyên nhân gốc rễ (ground truth): db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-076',
        "name": 'Sự cố #76: quá tải CPU tại docker_004 (container)',
        "description": 'Sự cố thật #76 (dataset DejaVu): thiết bị docker_004 (container) gặp \'quá tải CPU\' (mã gốc trong dữ liệu: "CPU fault"). Ghi nhận lúc 30/05/2020 20:17 UTC. Nguyên nhân gốc rễ (ground truth): docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-077',
        "name": 'Sự cố #77: độ trễ mạng cao bất thường tại docker_006 (container)',
        "description": 'Sự cố thật #77 (dataset DejaVu): thiết bị docker_006 (container) gặp \'độ trễ mạng cao bất thường\' (mã gốc trong dữ liệu: "network delay"). Ghi nhận lúc 30/05/2020 20:47 UTC. Nguyên nhân gốc rễ (ground truth): docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-078',
        "name": 'Sự cố #78: mất gói tin trên mạng tại docker_003 (container)',
        "description": 'Sự cố thật #78 (dataset DejaVu): thiết bị docker_003 (container) gặp \'mất gói tin trên mạng\' (mã gốc trong dữ liệu: "network loss"). Ghi nhận lúc 30/05/2020 21:48 UTC. Nguyên nhân gốc rễ (ground truth): docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
]
