"""Real fault-diagnosis data from NetManAIOps/DejaVu (ESEC/FSE'22, Li et al.,
Tsinghua) -- used as a real-data, cross-domain check for the KG + rule engine
+ GraphRAG pipeline built for the (synthetic) telecom scenarios.

Source: https://zenodo.org/records/6955909 (DOI 10.5281/zenodo.6955909),
license CC-BY 4.0 -- redistribution of this derived subset is permitted with
attribution, unlike the other real datasets considered (see README.md for
the full data-sourcing story: NetRCA's challenge infra was dead, TeleLogs is
gated + explicitly non-redistributable).

IMPORTANT CAVEAT: this is real microservice/infrastructure fault data
(Docker containers, DB instances, OS hosts calling each other), NOT telecom
network data. It is used here because its structure -- a real dependency
DAG with real fault injection and real ground-truth root-cause labels -- is
the same graph-theoretic shape (dependency graph + fault propagation + root
cause localization) as the telecom cascade problem this project targets, so
it is a legitimate generalization check, not a telecom dataset.

All incidents in this dataset are single-device, non-cascading faults
(root cause is always the same device that shows the fault) -- i.e. they
exercise the "isolated device fault" rule / structural-diagnosis path on a
messy real multi-parent DAG (unlike the synthetic telecom scenarios, which
specifically also test cascading multi-device attribution).

Regenerate with: python scripts/fetch_dejavu.py -- do not hand-edit.
"""

DEVICES = [
    {"id": 'db_003', "type": 'db', "name": 'db_003', "depends_on": []},
    {"id": 'db_007', "type": 'db', "name": 'db_007', "depends_on": []},
    {"id": 'db_009', "type": 'db', "name": 'db_009', "depends_on": []},
    {"id": 'docker_001', "type": 'docker', "name": 'docker_001', "depends_on": ['db_007', 'db_009', 'docker_007', 'docker_008', 'os_017']},
    {"id": 'docker_002', "type": 'docker', "name": 'docker_002', "depends_on": ['db_007', 'db_009', 'docker_007', 'docker_008', 'os_018']},
    {"id": 'docker_003', "type": 'docker', "name": 'docker_003', "depends_on": ['db_007', 'db_009', 'docker_005', 'docker_006', 'os_019']},
    {"id": 'docker_004', "type": 'docker', "name": 'docker_004', "depends_on": ['db_007', 'db_009', 'docker_005', 'docker_006', 'os_020']},
    {"id": 'docker_005', "type": 'docker', "name": 'docker_005', "depends_on": ['db_003', 'os_017']},
    {"id": 'docker_006', "type": 'docker', "name": 'docker_006', "depends_on": ['db_003', 'os_018']},
    {"id": 'docker_007', "type": 'docker', "name": 'docker_007', "depends_on": ['db_003', 'os_019']},
    {"id": 'docker_008', "type": 'docker', "name": 'docker_008', "depends_on": ['db_003', 'os_020']},
    {"id": 'os_017', "type": 'os', "name": 'os_017', "depends_on": []},
    {"id": 'os_018', "type": 'os', "name": 'os_018', "depends_on": []},
    {"id": 'os_019', "type": 'os', "name": 'os_019', "depends_on": []},
    {"id": 'os_020', "type": 'os', "name": 'os_020', "depends_on": []},
    {"id": 'os_021', "type": 'osb', "name": 'os_021', "depends_on": ['docker_003', 'docker_004']},
    {"id": 'os_022', "type": 'osb', "name": 'os_022', "depends_on": ['docker_001', 'docker_002']},
]

INCIDENTS = [
    {
        "id": 'DEJAVU-001',
        "name": 'CPU fault tren docker_003 (DejaVu #1, timestamp=1586534700)',
        "description": "Su co that tu dataset DejaVu: docker_003 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_003 CPU.",
        "alarms": [{'device': 'docker_003', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-002',
        "name": 'network delay tren docker_002 (DejaVu #2, timestamp=1586536500)',
        "description": "Su co that tu dataset DejaVu: docker_002 (Docker) gap 'network delay'. Ground truth root cause node: docker_002.",
        "alarms": [{'device': 'docker_002', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-003',
        "name": 'network delay tren docker_001 (DejaVu #3, timestamp=1586538600)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker) gap 'network delay'. Ground truth root cause node: docker_001.",
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-004',
        "name": 'CPU fault tren docker_004 (DejaVu #4, timestamp=1586540400)',
        "description": "Su co that tu dataset DejaVu: docker_004 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_004 CPU.",
        "alarms": [{'device': 'docker_004', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-005',
        "name": 'db connection limit tren db_007 (DejaVu #5, timestamp=1586542500)',
        "description": "Su co that tu dataset DejaVu: db_007 (DB Session) gap 'db connection limit'. Ground truth root cause node: db_007 Session.",
        "alarms": [{'device': 'db_007', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-006',
        "name": 'CPU fault tren docker_002 (DejaVu #6, timestamp=1586544600)',
        "description": "Su co that tu dataset DejaVu: docker_002 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_002 CPU.",
        "alarms": [{'device': 'docker_002', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-007',
        "name": 'network delay tren docker_003 (DejaVu #7, timestamp=1586546400)',
        "description": "Su co that tu dataset DejaVu: docker_003 (Docker) gap 'network delay'. Ground truth root cause node: docker_003.",
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-008',
        "name": 'network loss tren docker_003 (DejaVu #8, timestamp=1586548500)',
        "description": "Su co that tu dataset DejaVu: docker_003 (Docker) gap 'network loss'. Ground truth root cause node: docker_003.",
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-009',
        "name": 'CPU fault tren docker_008 (DejaVu #9, timestamp=1586551200)',
        "description": "Su co that tu dataset DejaVu: docker_008 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_008 CPU.",
        "alarms": [{'device': 'docker_008', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-010',
        "name": 'network loss tren docker_007 (DejaVu #10, timestamp=1586552700)',
        "description": "Su co that tu dataset DejaVu: docker_007 (Docker) gap 'network loss'. Ground truth root cause node: docker_007.",
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-011',
        "name": 'db  close tren db_003 (DejaVu #11, timestamp=1586555100)',
        "description": "Su co that tu dataset DejaVu: db_003 (DB State) gap 'db  close'. Ground truth root cause node: db_003 State.",
        "alarms": [{'device': 'db_003', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-012',
        "name": 'db  close tren db_003 (DejaVu #12, timestamp=1590077220)',
        "description": "Su co that tu dataset DejaVu: db_003 (DB State) gap 'db  close'. Ground truth root cause node: db_003 State.",
        "alarms": [{'device': 'db_003', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-013',
        "name": 'CPU fault tren docker_001 (DejaVu #13, timestamp=1590079680)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_001 CPU.",
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-014',
        "name": 'network delay tren docker_005 (DejaVu #14, timestamp=1590081480)',
        "description": "Su co that tu dataset DejaVu: docker_005 (Docker) gap 'network delay'. Ground truth root cause node: docker_005.",
        "alarms": [{'device': 'docker_005', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-015',
        "name": 'network delay tren os_018 (DejaVu #15, timestamp=1590083280)',
        "description": "Su co that tu dataset DejaVu: os_018 (OS Network) gap 'network delay'. Ground truth root cause node: os_018 Network.",
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-016',
        "name": 'CPU fault tren docker_005 (DejaVu #16, timestamp=1590085080)',
        "description": "Su co that tu dataset DejaVu: docker_005 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_005 CPU.",
        "alarms": [{'device': 'docker_005', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-017',
        "name": 'network delay tren docker_007 (DejaVu #17, timestamp=1590095880)',
        "description": "Su co that tu dataset DejaVu: docker_007 (Docker) gap 'network delay'. Ground truth root cause node: docker_007.",
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-018',
        "name": 'network delay tren docker_006 (DejaVu #18, timestamp=1590097680)',
        "description": "Su co that tu dataset DejaVu: docker_006 (Docker) gap 'network delay'. Ground truth root cause node: docker_006.",
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-019',
        "name": 'CPU fault tren docker_004 (DejaVu #19, timestamp=1590163500)',
        "description": "Su co that tu dataset DejaVu: docker_004 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_004 CPU.",
        "alarms": [{'device': 'docker_004', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-020',
        "name": 'db connection limit tren db_003 (DejaVu #20, timestamp=1590165600)',
        "description": "Su co that tu dataset DejaVu: db_003 (DB Session) gap 'db connection limit'. Ground truth root cause node: db_003 Session.",
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-021',
        "name": 'network loss tren os_021 (DejaVu #21, timestamp=1590167760)',
        "description": "Su co that tu dataset DejaVu: os_021 (OS Network) gap 'network loss'. Ground truth root cause node: os_021 Network.",
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-022',
        "name": 'network delay tren docker_006 (DejaVu #22, timestamp=1590174000)',
        "description": "Su co that tu dataset DejaVu: docker_006 (Docker) gap 'network delay'. Ground truth root cause node: docker_006.",
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-023',
        "name": 'network delay tren os_021 (DejaVu #23, timestamp=1590176160)',
        "description": "Su co that tu dataset DejaVu: os_021 (OS Network) gap 'network delay'. Ground truth root cause node: os_021 Network.",
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-024',
        "name": 'CPU fault tren docker_006 (DejaVu #24, timestamp=1590180420)',
        "description": "Su co that tu dataset DejaVu: docker_006 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_006 CPU.",
        "alarms": [{'device': 'docker_006', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-025',
        "name": 'network delay tren docker_005 (DejaVu #25, timestamp=1590182400)',
        "description": "Su co that tu dataset DejaVu: docker_005 (Docker) gap 'network delay'. Ground truth root cause node: docker_005.",
        "alarms": [{'device': 'docker_005', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-026',
        "name": 'network loss tren docker_007 (DejaVu #26, timestamp=1590184500)',
        "description": "Su co that tu dataset DejaVu: docker_007 (Docker) gap 'network loss'. Ground truth root cause node: docker_007.",
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-027',
        "name": 'network loss tren docker_004 (DejaVu #27, timestamp=1590250620)',
        "description": "Su co that tu dataset DejaVu: docker_004 (Docker) gap 'network loss'. Ground truth root cause node: docker_004.",
        "alarms": [{'device': 'docker_004', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-028',
        "name": 'db  close tren db_007 (DejaVu #28, timestamp=1590256020)',
        "description": "Su co that tu dataset DejaVu: db_007 (DB State) gap 'db  close'. Ground truth root cause node: db_007 State.",
        "alarms": [{'device': 'db_007', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-029',
        "name": 'network loss tren docker_002 (DejaVu #29, timestamp=1590259620)',
        "description": "Su co that tu dataset DejaVu: docker_002 (Docker) gap 'network loss'. Ground truth root cause node: docker_002.",
        "alarms": [{'device': 'docker_002', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-030',
        "name": 'CPU fault tren docker_003 (DejaVu #30, timestamp=1590261420)',
        "description": "Su co that tu dataset DejaVu: docker_003 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_003 CPU.",
        "alarms": [{'device': 'docker_003', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-031',
        "name": 'CPU fault tren docker_006 (DejaVu #31, timestamp=1590265020)',
        "description": "Su co that tu dataset DejaVu: docker_006 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_006 CPU.",
        "alarms": [{'device': 'docker_006', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-032',
        "name": 'network delay tren docker_004 (DejaVu #32, timestamp=1590266820)',
        "description": "Su co that tu dataset DejaVu: docker_004 (Docker) gap 'network delay'. Ground truth root cause node: docker_004.",
        "alarms": [{'device': 'docker_004', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-033',
        "name": 'network delay tren os_020 (DejaVu #33, timestamp=1590342420)',
        "description": "Su co that tu dataset DejaVu: os_020 (OS Network) gap 'network delay'. Ground truth root cause node: os_020 Network.",
        "alarms": [{'device': 'os_020', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_020',
    },
    {
        "id": 'DEJAVU-034',
        "name": 'network loss tren os_017 (DejaVu #34, timestamp=1590349620)',
        "description": "Su co that tu dataset DejaVu: os_017 (OS Network) gap 'network loss'. Ground truth root cause node: os_017 Network.",
        "alarms": [{'device': 'os_017', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_017',
    },
    {
        "id": 'DEJAVU-035',
        "name": 'db  close tren db_003 (DejaVu #35, timestamp=1590353220)',
        "description": "Su co that tu dataset DejaVu: db_003 (DB State) gap 'db  close'. Ground truth root cause node: db_003 State.",
        "alarms": [{'device': 'db_003', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-036',
        "name": 'network loss tren docker_003 (DejaVu #36, timestamp=1590424320)',
        "description": "Su co that tu dataset DejaVu: docker_003 (Docker) gap 'network loss'. Ground truth root cause node: docker_003.",
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-037',
        "name": 'db connection limit tren db_007 (DejaVu #37, timestamp=1590430140)',
        "description": "Su co that tu dataset DejaVu: db_007 (DB Session) gap 'db connection limit'. Ground truth root cause node: db_007 Session.",
        "alarms": [{'device': 'db_007', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-038',
        "name": 'CPU fault tren docker_008 (DejaVu #38, timestamp=1590431940)',
        "description": "Su co that tu dataset DejaVu: docker_008 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_008 CPU.",
        "alarms": [{'device': 'docker_008', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-039',
        "name": 'network delay tren os_021 (DejaVu #39, timestamp=1590433740)',
        "description": "Su co that tu dataset DejaVu: os_021 (OS Network) gap 'network delay'. Ground truth root cause node: os_021 Network.",
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-040',
        "name": 'network loss tren os_018 (DejaVu #40, timestamp=1590435540)',
        "description": "Su co that tu dataset DejaVu: os_018 (OS Network) gap 'network loss'. Ground truth root cause node: os_018 Network.",
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-041',
        "name": 'network delay tren os_020 (DejaVu #41, timestamp=1590437700)',
        "description": "Su co that tu dataset DejaVu: os_020 (OS Network) gap 'network delay'. Ground truth root cause node: os_020 Network.",
        "alarms": [{'device': 'os_020', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_020',
    },
    {
        "id": 'DEJAVU-042',
        "name": 'CPU fault tren docker_002 (DejaVu #42, timestamp=1590441300)',
        "description": "Su co that tu dataset DejaVu: docker_002 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_002 CPU.",
        "alarms": [{'device': 'docker_002', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-043',
        "name": 'network delay tren os_018 (DejaVu #43, timestamp=1590510180)',
        "description": "Su co that tu dataset DejaVu: os_018 (OS Network) gap 'network delay'. Ground truth root cause node: os_018 Network.",
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-044',
        "name": 'network delay tren os_017 (DejaVu #44, timestamp=1590511980)',
        "description": "Su co that tu dataset DejaVu: os_017 (OS Network) gap 'network delay'. Ground truth root cause node: os_017 Network.",
        "alarms": [{'device': 'os_017', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_017',
    },
    {
        "id": 'DEJAVU-045',
        "name": 'CPU fault tren docker_006 (DejaVu #45, timestamp=1590513780)',
        "description": "Su co that tu dataset DejaVu: docker_006 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_006 CPU.",
        "alarms": [{'device': 'docker_006', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-046',
        "name": 'db connection limit tren db_003 (DejaVu #46, timestamp=1590515580)',
        "description": "Su co that tu dataset DejaVu: db_003 (DB Session) gap 'db connection limit'. Ground truth root cause node: db_003 Session.",
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-047',
        "name": 'db  close tren db_007 (DejaVu #47, timestamp=1590517380)',
        "description": "Su co that tu dataset DejaVu: db_007 (DB State) gap 'db  close'. Ground truth root cause node: db_007 State.",
        "alarms": [{'device': 'db_007', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-048',
        "name": 'db connection limit tren db_007 (DejaVu #48, timestamp=1590519180)',
        "description": "Su co that tu dataset DejaVu: db_007 (DB Session) gap 'db connection limit'. Ground truth root cause node: db_007 Session.",
        "alarms": [{'device': 'db_007', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-049',
        "name": 'network delay tren docker_001 (DejaVu #49, timestamp=1590520980)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker) gap 'network delay'. Ground truth root cause node: docker_001.",
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-050',
        "name": 'network loss tren docker_007 (DejaVu #50, timestamp=1590525540)',
        "description": "Su co that tu dataset DejaVu: docker_007 (Docker) gap 'network loss'. Ground truth root cause node: docker_007.",
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-051',
        "name": 'CPU fault tren docker_001 (DejaVu #51, timestamp=1590527340)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_001 CPU.",
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-052',
        "name": 'network delay tren os_021 (DejaVu #52, timestamp=1590529140)',
        "description": "Su co that tu dataset DejaVu: os_021 (OS Network) gap 'network delay'. Ground truth root cause node: os_021 Network.",
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-053',
        "name": 'CPU fault tren docker_001 (DejaVu #53, timestamp=1590598020)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_001 CPU.",
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-054',
        "name": 'network delay tren docker_001 (DejaVu #54, timestamp=1590599820)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker) gap 'network delay'. Ground truth root cause node: docker_001.",
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-055',
        "name": 'network delay tren docker_001 (DejaVu #55, timestamp=1590607020)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker) gap 'network delay'. Ground truth root cause node: docker_001.",
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-056',
        "name": 'network loss tren os_018 (DejaVu #56, timestamp=1590608820)',
        "description": "Su co that tu dataset DejaVu: os_018 (OS Network) gap 'network loss'. Ground truth root cause node: os_018 Network.",
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-057',
        "name": 'network loss tren docker_008 (DejaVu #57, timestamp=1590614220)',
        "description": "Su co that tu dataset DejaVu: docker_008 (Docker) gap 'network loss'. Ground truth root cause node: docker_008.",
        "alarms": [{'device': 'docker_008', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-058',
        "name": 'db connection limit tren db_003 (DejaVu #58, timestamp=1590689460)',
        "description": "Su co that tu dataset DejaVu: db_003 (DB Session) gap 'db connection limit'. Ground truth root cause node: db_003 Session.",
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-059',
        "name": 'CPU fault tren docker_008 (DejaVu #59, timestamp=1590691260)',
        "description": "Su co that tu dataset DejaVu: docker_008 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_008 CPU.",
        "alarms": [{'device': 'docker_008', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-060',
        "name": 'CPU fault tren docker_001 (DejaVu #60, timestamp=1590694860)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_001 CPU.",
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-061',
        "name": 'network delay tren docker_006 (DejaVu #61, timestamp=1590700260)',
        "description": "Su co that tu dataset DejaVu: docker_006 (Docker) gap 'network delay'. Ground truth root cause node: docker_006.",
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-062',
        "name": 'network loss tren os_021 (DejaVu #62, timestamp=1590768780)',
        "description": "Su co that tu dataset DejaVu: os_021 (OS Network) gap 'network loss'. Ground truth root cause node: os_021 Network.",
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-063',
        "name": 'network loss tren docker_005 (DejaVu #63, timestamp=1590770580)',
        "description": "Su co that tu dataset DejaVu: docker_005 (Docker) gap 'network loss'. Ground truth root cause node: docker_005.",
        "alarms": [{'device': 'docker_005', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-064',
        "name": 'network loss tren docker_001 (DejaVu #64, timestamp=1590775980)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker) gap 'network loss'. Ground truth root cause node: docker_001.",
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-065',
        "name": 'network delay tren os_020 (DejaVu #65, timestamp=1590781380)',
        "description": "Su co that tu dataset DejaVu: os_020 (OS Network) gap 'network delay'. Ground truth root cause node: os_020 Network.",
        "alarms": [{'device': 'os_020', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_020',
    },
    {
        "id": 'DEJAVU-066',
        "name": 'CPU fault tren docker_002 (DejaVu #66, timestamp=1590783180)',
        "description": "Su co that tu dataset DejaVu: docker_002 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_002 CPU.",
        "alarms": [{'device': 'docker_002', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-067',
        "name": 'network loss tren os_018 (DejaVu #67, timestamp=1590786780)',
        "description": "Su co that tu dataset DejaVu: os_018 (OS Network) gap 'network loss'. Ground truth root cause node: os_018 Network.",
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-068',
        "name": 'network delay tren docker_002 (DejaVu #68, timestamp=1590788580)',
        "description": "Su co that tu dataset DejaVu: docker_002 (Docker) gap 'network delay'. Ground truth root cause node: docker_002.",
        "alarms": [{'device': 'docker_002', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-069',
        "name": 'network delay tren docker_007 (DejaVu #69, timestamp=1590855420)',
        "description": "Su co that tu dataset DejaVu: docker_007 (Docker) gap 'network delay'. Ground truth root cause node: docker_007.",
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-070',
        "name": 'network delay tren docker_001 (DejaVu #70, timestamp=1590857220)',
        "description": "Su co that tu dataset DejaVu: docker_001 (Docker) gap 'network delay'. Ground truth root cause node: docker_001.",
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-071',
        "name": 'network loss tren docker_008 (DejaVu #71, timestamp=1590860820)',
        "description": "Su co that tu dataset DejaVu: docker_008 (Docker) gap 'network loss'. Ground truth root cause node: docker_008.",
        "alarms": [{'device': 'docker_008', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-072',
        "name": 'network delay tren docker_008 (DejaVu #72, timestamp=1590862620)',
        "description": "Su co that tu dataset DejaVu: docker_008 (Docker) gap 'network delay'. Ground truth root cause node: docker_008.",
        "alarms": [{'device': 'docker_008', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-073',
        "name": 'network delay tren os_021 (DejaVu #73, timestamp=1590864420)',
        "description": "Su co that tu dataset DejaVu: os_021 (OS Network) gap 'network delay'. Ground truth root cause node: os_021 Network.",
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-074',
        "name": 'network delay tren os_017 (DejaVu #74, timestamp=1590866220)',
        "description": "Su co that tu dataset DejaVu: os_017 (OS Network) gap 'network delay'. Ground truth root cause node: os_017 Network.",
        "alarms": [{'device': 'os_017', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_017',
    },
    {
        "id": 'DEJAVU-075',
        "name": 'db connection limit tren db_003 (DejaVu #75, timestamp=1590868020)',
        "description": "Su co that tu dataset DejaVu: db_003 (DB Session) gap 'db connection limit'. Ground truth root cause node: db_003 Session.",
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-076',
        "name": 'CPU fault tren docker_004 (DejaVu #76, timestamp=1590869820)',
        "description": "Su co that tu dataset DejaVu: docker_004 (Docker CPU) gap 'CPU fault'. Ground truth root cause node: docker_004 CPU.",
        "alarms": [{'device': 'docker_004', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-077',
        "name": 'network delay tren docker_006 (DejaVu #77, timestamp=1590871620)',
        "description": "Su co that tu dataset DejaVu: docker_006 (Docker) gap 'network delay'. Ground truth root cause node: docker_006.",
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-078',
        "name": 'network loss tren docker_003 (DejaVu #78, timestamp=1590875280)',
        "description": "Su co that tu dataset DejaVu: docker_003 (Docker) gap 'network loss'. Ground truth root cause node: docker_003.",
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
]
