"""Real fault-diagnosis data from NetManAIOps/DejaVu (ESEC/FSE'22, Li et al.,
Tsinghua) -- used as a real-data, cross-domain check for the KG + rule engine
+ GraphRAG pipeline built for the (synthetic) telecom scenarios.

Source: https://zenodo.org/records/6955909 (DOI 10.5281/zenodo.6955909),
license CC-BY 4.0 -- redistribution of this derived subset is permitted with
attribution, unlike the other real datasets considered (see README.md for
the full data-sourcing story: NetRCA's challenge infra was dead, TeleLogs is
gated + explicitly non-redistributable).

IMPORTANT CAVEAT: this is real microservice/infrastructure fault data
(Docker containers, DB instances, OS hosts calling each other), NOT telecom
network data. It is used here because its structure -- a real dependency
DAG with real fault injection and real ground-truth root-cause labels -- is
the same graph-theoretic shape (dependency graph + fault propagation + root
cause localization) as the telecom cascade problem this project targets, so
it is a legitimate generalization check, not a telecom dataset.

All incidents in this dataset are single-device, non-cascading faults
(root cause is always the same device that shows the fault) -- i.e. they
exercise the "isolated device fault" rule / structural-diagnosis path on a
messy real multi-parent DAG (unlike the synthetic telecom scenarios, which
specifically also test cascading multi-device attribution).

Regenerate with: python scripts/fetch_dejavu.py -- do not hand-edit.
"""

DEVICES = [
    {"id": 'db_003', "type": 'db', "name": 'db_003', "depends_on": []},
    {"id": 'db_007', "type": 'db', "name": 'db_007', "depends_on": []},
    {"id": 'db_009', "type": 'db', "name": 'db_009', "depends_on": []},
    {"id": 'docker_001', "type": 'docker', "name": 'docker_001', "depends_on": ['db_007', 'db_009', 'docker_007', 'docker_008', 'os_017']},
    {"id": 'docker_002', "type": 'docker', "name": 'docker_002', "depends_on": ['db_007', 'db_009', 'docker_007', 'docker_008', 'os_018']},
    {"id": 'docker_003', "type": 'docker', "name": 'docker_003', "depends_on": ['db_007', 'db_009', 'docker_005', 'docker_006', 'os_019']},
    {"id": 'docker_004', "type": 'docker', "name": 'docker_004', "depends_on": ['db_007', 'db_009', 'docker_005', 'docker_006', 'os_020']},
    {"id": 'docker_005', "type": 'docker', "name": 'docker_005', "depends_on": ['db_003', 'os_017']},
    {"id": 'docker_006', "type": 'docker', "name": 'docker_006', "depends_on": ['db_003', 'os_018']},
    {"id": 'docker_007', "type": 'docker', "name": 'docker_007', "depends_on": ['db_003', 'os_019']},
    {"id": 'docker_008', "type": 'docker', "name": 'docker_008', "depends_on": ['db_003', 'os_020']},
    {"id": 'os_017', "type": 'os', "name": 'os_017', "depends_on": []},
    {"id": 'os_018', "type": 'os', "name": 'os_018', "depends_on": []},
    {"id": 'os_019', "type": 'os', "name": 'os_019', "depends_on": []},
    {"id": 'os_020', "type": 'os', "name": 'os_020', "depends_on": []},
    {"id": 'os_021', "type": 'osb', "name": 'os_021', "depends_on": ['docker_003', 'docker_004']},
    {"id": 'os_022', "type": 'osb', "name": 'os_022', "depends_on": ['docker_001', 'docker_002']},
]

INCIDENTS = [
    {
        "id": 'DEJAVU-001',
        "name": '#1: docker_003 bị quá tải CPU',
        "description": 'docker_003 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-002',
        "name": '#2: docker_002 bị độ trễ mạng cao bất thường',
        "description": 'docker_002 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-003',
        "name": '#3: docker_001 bị độ trễ mạng cao bất thường',
        "description": 'docker_001 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-004',
        "name": '#4: docker_004 bị quá tải CPU',
        "description": 'docker_004 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-005',
        "name": '#5: db_007 bị vượt giới hạn số kết nối database',
        "description": 'db_007 (database) đang bị vượt giới hạn số kết nối database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-006',
        "name": '#6: docker_002 bị quá tải CPU',
        "description": 'docker_002 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-007',
        "name": '#7: docker_003 bị độ trễ mạng cao bất thường',
        "description": 'docker_003 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-008',
        "name": '#8: docker_003 bị mất gói tin trên mạng',
        "description": 'docker_003 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-009',
        "name": '#9: docker_008 bị quá tải CPU',
        "description": 'docker_008 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-010',
        "name": '#10: docker_007 bị mất gói tin trên mạng',
        "description": 'docker_007 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-011',
        "name": '#11: db_003 bị mất kết nối / đóng phiên database',
        "description": 'db_003 (database) đang bị mất kết nối / đóng phiên database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 10/04/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-012',
        "name": '#12: db_003 bị mất kết nối / đóng phiên database',
        "description": 'db_003 (database) đang bị mất kết nối / đóng phiên database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 21/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-013',
        "name": '#13: docker_001 bị quá tải CPU',
        "description": 'docker_001 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 21/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-014',
        "name": '#14: docker_005 bị độ trễ mạng cao bất thường',
        "description": 'docker_005 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 21/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_005.',
        "alarms": [{'device': 'docker_005', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-015',
        "name": '#15: os_018 bị độ trễ mạng cao bất thường',
        "description": 'os_018 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 21/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-016',
        "name": '#16: docker_005 bị quá tải CPU',
        "description": 'docker_005 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 21/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_005.',
        "alarms": [{'device': 'docker_005', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-017',
        "name": '#17: docker_007 bị độ trễ mạng cao bất thường',
        "description": 'docker_007 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 21/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-018',
        "name": '#18: docker_006 bị độ trễ mạng cao bất thường',
        "description": 'docker_006 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 21/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-019',
        "name": '#19: docker_004 bị quá tải CPU',
        "description": 'docker_004 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 22/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-020',
        "name": '#20: db_003 bị vượt giới hạn số kết nối database',
        "description": 'db_003 (database) đang bị vượt giới hạn số kết nối database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 22/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-021',
        "name": '#21: os_021 bị mất gói tin trên mạng',
        "description": 'os_021 (máy chủ vật lý (host)) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 22/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-022',
        "name": '#22: docker_006 bị độ trễ mạng cao bất thường',
        "description": 'docker_006 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 22/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-023',
        "name": '#23: os_021 bị độ trễ mạng cao bất thường',
        "description": 'os_021 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 22/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-024',
        "name": '#24: docker_006 bị quá tải CPU',
        "description": 'docker_006 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 22/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-025',
        "name": '#25: docker_005 bị độ trễ mạng cao bất thường',
        "description": 'docker_005 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 22/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_005.',
        "alarms": [{'device': 'docker_005', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-026',
        "name": '#26: docker_007 bị mất gói tin trên mạng',
        "description": 'docker_007 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 22/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-027',
        "name": '#27: docker_004 bị mất gói tin trên mạng',
        "description": 'docker_004 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 23/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-028',
        "name": '#28: db_007 bị mất kết nối / đóng phiên database',
        "description": 'db_007 (database) đang bị mất kết nối / đóng phiên database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 23/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-029',
        "name": '#29: docker_002 bị mất gói tin trên mạng',
        "description": 'docker_002 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 23/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-030',
        "name": '#30: docker_003 bị quá tải CPU',
        "description": 'docker_003 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 23/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-031',
        "name": '#31: docker_006 bị quá tải CPU',
        "description": 'docker_006 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 23/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-032',
        "name": '#32: docker_004 bị độ trễ mạng cao bất thường',
        "description": 'docker_004 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 23/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-033',
        "name": '#33: os_020 bị độ trễ mạng cao bất thường',
        "description": 'os_020 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 24/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_020.',
        "alarms": [{'device': 'os_020', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_020',
    },
    {
        "id": 'DEJAVU-034',
        "name": '#34: os_017 bị mất gói tin trên mạng',
        "description": 'os_017 (máy chủ vật lý (host)) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 24/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_017.',
        "alarms": [{'device': 'os_017', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_017',
    },
    {
        "id": 'DEJAVU-035',
        "name": '#35: db_003 bị mất kết nối / đóng phiên database',
        "description": 'db_003 (database) đang bị mất kết nối / đóng phiên database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 24/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-036',
        "name": '#36: docker_003 bị mất gói tin trên mạng',
        "description": 'docker_003 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 25/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
    {
        "id": 'DEJAVU-037',
        "name": '#37: db_007 bị vượt giới hạn số kết nối database',
        "description": 'db_007 (database) đang bị vượt giới hạn số kết nối database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 25/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-038',
        "name": '#38: docker_008 bị quá tải CPU',
        "description": 'docker_008 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 25/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-039',
        "name": '#39: os_021 bị độ trễ mạng cao bất thường',
        "description": 'os_021 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 25/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-040',
        "name": '#40: os_018 bị mất gói tin trên mạng',
        "description": 'os_018 (máy chủ vật lý (host)) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 25/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-041',
        "name": '#41: os_020 bị độ trễ mạng cao bất thường',
        "description": 'os_020 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 25/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_020.',
        "alarms": [{'device': 'os_020', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_020',
    },
    {
        "id": 'DEJAVU-042',
        "name": '#42: docker_002 bị quá tải CPU',
        "description": 'docker_002 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 25/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-043',
        "name": '#43: os_018 bị độ trễ mạng cao bất thường',
        "description": 'os_018 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-044',
        "name": '#44: os_017 bị độ trễ mạng cao bất thường',
        "description": 'os_017 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_017.',
        "alarms": [{'device': 'os_017', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_017',
    },
    {
        "id": 'DEJAVU-045',
        "name": '#45: docker_006 bị quá tải CPU',
        "description": 'docker_006 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-046',
        "name": '#46: db_003 bị vượt giới hạn số kết nối database',
        "description": 'db_003 (database) đang bị vượt giới hạn số kết nối database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-047',
        "name": '#47: db_007 bị mất kết nối / đóng phiên database',
        "description": 'db_007 (database) đang bị mất kết nối / đóng phiên database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CLOSE', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-048',
        "name": '#48: db_007 bị vượt giới hạn số kết nối database',
        "description": 'db_007 (database) đang bị vượt giới hạn số kết nối database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_007.',
        "alarms": [{'device': 'db_007', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_007',
    },
    {
        "id": 'DEJAVU-049',
        "name": '#49: docker_001 bị độ trễ mạng cao bất thường',
        "description": 'docker_001 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-050',
        "name": '#50: docker_007 bị mất gói tin trên mạng',
        "description": 'docker_007 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-051',
        "name": '#51: docker_001 bị quá tải CPU',
        "description": 'docker_001 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-052',
        "name": '#52: os_021 bị độ trễ mạng cao bất thường',
        "description": 'os_021 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 26/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-053',
        "name": '#53: docker_001 bị quá tải CPU',
        "description": 'docker_001 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 27/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-054',
        "name": '#54: docker_001 bị độ trễ mạng cao bất thường',
        "description": 'docker_001 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 27/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-055',
        "name": '#55: docker_001 bị độ trễ mạng cao bất thường',
        "description": 'docker_001 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 27/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-056',
        "name": '#56: os_018 bị mất gói tin trên mạng',
        "description": 'os_018 (máy chủ vật lý (host)) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 27/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-057',
        "name": '#57: docker_008 bị mất gói tin trên mạng',
        "description": 'docker_008 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 27/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-058',
        "name": '#58: db_003 bị vượt giới hạn số kết nối database',
        "description": 'db_003 (database) đang bị vượt giới hạn số kết nối database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 28/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-059',
        "name": '#59: docker_008 bị quá tải CPU',
        "description": 'docker_008 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 28/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-060',
        "name": '#60: docker_001 bị quá tải CPU',
        "description": 'docker_001 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 28/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-061',
        "name": '#61: docker_006 bị độ trễ mạng cao bất thường',
        "description": 'docker_006 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 28/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-062',
        "name": '#62: os_021 bị mất gói tin trên mạng',
        "description": 'os_021 (máy chủ vật lý (host)) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 29/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-063',
        "name": '#63: docker_005 bị mất gói tin trên mạng',
        "description": 'docker_005 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 29/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_005.',
        "alarms": [{'device': 'docker_005', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_005',
    },
    {
        "id": 'DEJAVU-064',
        "name": '#64: docker_001 bị mất gói tin trên mạng',
        "description": 'docker_001 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 29/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-065',
        "name": '#65: os_020 bị độ trễ mạng cao bất thường',
        "description": 'os_020 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 29/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_020.',
        "alarms": [{'device': 'os_020', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_020',
    },
    {
        "id": 'DEJAVU-066',
        "name": '#66: docker_002 bị quá tải CPU',
        "description": 'docker_002 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 29/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-067',
        "name": '#67: os_018 bị mất gói tin trên mạng',
        "description": 'os_018 (máy chủ vật lý (host)) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 29/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_018.',
        "alarms": [{'device': 'os_018', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_018',
    },
    {
        "id": 'DEJAVU-068',
        "name": '#68: docker_002 bị độ trễ mạng cao bất thường',
        "description": 'docker_002 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 29/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_002.',
        "alarms": [{'device': 'docker_002', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_002',
    },
    {
        "id": 'DEJAVU-069',
        "name": '#69: docker_007 bị độ trễ mạng cao bất thường',
        "description": 'docker_007 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_007.',
        "alarms": [{'device': 'docker_007', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_007',
    },
    {
        "id": 'DEJAVU-070',
        "name": '#70: docker_001 bị độ trễ mạng cao bất thường',
        "description": 'docker_001 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_001.',
        "alarms": [{'device': 'docker_001', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_001',
    },
    {
        "id": 'DEJAVU-071',
        "name": '#71: docker_008 bị mất gói tin trên mạng',
        "description": 'docker_008 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-072',
        "name": '#72: docker_008 bị độ trễ mạng cao bất thường',
        "description": 'docker_008 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_008.',
        "alarms": [{'device': 'docker_008', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_008',
    },
    {
        "id": 'DEJAVU-073',
        "name": '#73: os_021 bị độ trễ mạng cao bất thường',
        "description": 'os_021 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_021.',
        "alarms": [{'device': 'os_021', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_021',
    },
    {
        "id": 'DEJAVU-074',
        "name": '#74: os_017 bị độ trễ mạng cao bất thường',
        "description": 'os_017 (máy chủ vật lý (host)) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là os_017.',
        "alarms": [{'device': 'os_017', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'os_017',
    },
    {
        "id": 'DEJAVU-075',
        "name": '#75: db_003 bị vượt giới hạn số kết nối database',
        "description": 'db_003 (database) đang bị vượt giới hạn số kết nối database — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là db_003.',
        "alarms": [{'device': 'db_003', 'type': 'DB_CONNECTION_LIMIT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'db_003',
    },
    {
        "id": 'DEJAVU-076',
        "name": '#76: docker_004 bị quá tải CPU',
        "description": 'docker_004 (container) đang bị quá tải CPU — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_004.',
        "alarms": [{'device': 'docker_004', 'type': 'CPU_FAULT', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_004',
    },
    {
        "id": 'DEJAVU-077',
        "name": '#77: docker_006 bị độ trễ mạng cao bất thường',
        "description": 'docker_006 (container) đang bị độ trễ mạng cao bất thường — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_006.',
        "alarms": [{'device': 'docker_006', 'type': 'NETWORK_DELAY', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_006',
    },
    {
        "id": 'DEJAVU-078',
        "name": '#78: docker_003 bị mất gói tin trên mạng',
        "description": 'docker_003 (container) đang bị mất gói tin trên mạng — đây là sự cố THẬT (không phải giả lập), xảy ra ngày 30/05/2020, lấy từ bộ dữ liệu công khai DejaVu. Đáp án đúng đã biết trước: chính là docker_003.',
        "alarms": [{'device': 'docker_003', 'type': 'NETWORK_LOSS', 'severity': 'major'}],
        "kpi_anomalies": [],
        "ground_truth_root_cause": 'docker_003',
    },
]
